services:
  auth:
    build: ./auth
    volumes:
      - ./auth/auth.py:/app/auth.py
    networks:
      - webnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.auth.loadbalancer.server.port=5000"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`, `/health`)"
      - "traefik.http.routers.auth.entrypoints=web"

  traefik:
    image: traefik:latest
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/traefik.yml"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
    ports:
      - "8080:80"
      - "8081:8080" # optional dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
    networks:
      - webnet

networks:
  webnet: